#!/usr/bin/env python3
"""
Cold Path Extractor for Android APKs.

This script bridges uncovered branch reports (generated by branch_coverage_analysis.py)
and static bytecode context (via AndroGuard) to produce LLM-ready prompts for probe generation.

Inputs supported:
- uncovered_branches.txt (one BRANCH=... line per row)
- uncovered_branches.csv (columns: Class,Branch)

Output:
- Markdown prompts file (default: cold_path_prompts.md)
- Optional JSONL file with structured records

Example:
    python probe_gen.py \
      --apk fse-dataset/Time_Planner_Schedule.apk \
      --uncovered uncovered_branches.txt \
      --top 20 \
      --out-md cold_path_prompts.md \
      --out-jsonl cold_path_prompts.jsonl
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

try:
    from tqdm import tqdm
except Exception:  # pragma: no cover
    def tqdm(iterable, **kwargs):  # type: ignore
        return iterable

try:
    from androguard.misc import AnalyzeAPK
except Exception as exc:  # pragma: no cover
    raise SystemExit(
        "Failed to import androguard. Install with: pip install androguard\n"
        f"Import error: {exc}"
    )


FRAMEWORK_PREFIXES: Tuple[str, ...] = (
    "Landroid/",
    "Landroidx/",
    "Ljava/",
    "Ljavax/",
    "Lkotlin/",
    "Lcom/google/",
)

BRANCH_RE = re.compile(
    r"<(?P<class_method>.+)>\|(?P<branch_type>IF|SWITCH)\|(?P<uid>U[0-9a-fA-F]+)"
    r"\|EDGE=(?P<edge>TRUE|FALSE)\|COND=(?P<cond>.*)$"
)

METHOD_SIG_RE = re.compile(
    r"^(?P<class_name>[^:]+):\s+(?P<ret_type>\S+)\s+(?P<method_name>[^\(]+)\((?P<params>.*)\)$"
)


@dataclass(frozen=True)
class BranchRecord:
    raw: str
    class_name: str
    method_name: str
    return_type: str
    params: str
    branch_type: str
    uid: str
    edge: str
    cond: str


@dataclass
class MethodContext:
    class_name: str
    method_name: str
    descriptor: str
    instruction_count: int
    instructions: List[str]


def normalize_branch_line(line: str) -> str:
    line = line.strip()
    if not line:
        return ""
    if line.startswith("BRANCH="):
        return line
    return f"BRANCH={line}"


def is_app_class(dex_class_name: str) -> bool:
    return not dex_class_name.startswith(FRAMEWORK_PREFIXES)


def parse_branch_record(line: str) -> Optional[BranchRecord]:
    line = normalize_branch_line(line)
    if not line:
        return None

    payload = line[len("BRANCH=") :]
    match = BRANCH_RE.match(payload)
    if not match:
        return None

    class_method = match.group("class_method")
    sig_match = METHOD_SIG_RE.match(class_method)
    if not sig_match:
        return None

    class_name = sig_match.group("class_name").strip()
    method_name = sig_match.group("method_name").strip()
    return_type = sig_match.group("ret_type").strip()
    params = sig_match.group("params").strip()

    return BranchRecord(
        raw=line,
        class_name=class_name,
        method_name=method_name,
        return_type=return_type,
        params=params,
        branch_type=match.group("branch_type"),
        uid=match.group("uid"),
        edge=match.group("edge"),
        cond=match.group("cond").strip(),
    )


def read_uncovered_file(path: str) -> List[BranchRecord]:
    if not os.path.exists(path):
        raise FileNotFoundError(f"Uncovered branch file not found: {path}")

    records: List[BranchRecord] = []
    seen_raw = set()

    if path.lower().endswith(".csv"):
        with open(path, "r", encoding="utf-8", errors="ignore", newline="") as handle:
            reader = csv.DictReader(handle)
            for row in reader:
                branch_value = (row.get("Branch") or "").strip()
                rec = parse_branch_record(branch_value)
                if rec and rec.raw not in seen_raw:
                    records.append(rec)
                    seen_raw.add(rec.raw)
    else:
        with open(path, "r", encoding="utf-8", errors="ignore") as handle:
            for line in handle:
                rec = parse_branch_record(line)
                if rec and rec.raw not in seen_raw:
                    records.append(rec)
                    seen_raw.add(rec.raw)

    return records


def build_method_index(dx) -> Dict[Tuple[str, str], List]:
    """
    Index by (class_name, method_name).
    class_name is in Soot-like format from branch logs, e.g. 'a0.a'.
    DEX class names are like 'La0/a;'.
    """
    index: Dict[Tuple[str, str], List] = {}

    for m_analysis in dx.get_methods():
        if m_analysis.is_external():
            continue

        method = m_analysis.get_method()
        dex_cls = method.get_class_name()  # e.g. La0/a;
        if not is_app_class(dex_cls):
            continue

        soot_like = dex_cls[1:-1].replace("/", ".")
        key = (soot_like, method.get_name())
        index.setdefault(key, []).append(m_analysis)

    return index


def extract_method_context(m_analysis, max_instructions: int) -> MethodContext:
    method = m_analysis.get_method()
    desc = method.get_descriptor()

    insns: List[str] = []
    encoded = method.get_code()
    if encoded is not None:
        bc = encoded.get_bc()
        if bc is not None:
            for idx, ins in enumerate(bc.get_instructions()):
                if idx >= max_instructions:
                    break
                # Keep concise and deterministic formatting.
                insns.append(f"{ins.get_name()} {ins.get_output()}")

    return MethodContext(
        class_name=method.get_class_name(),
        method_name=method.get_name(),
        descriptor=desc,
        instruction_count=len(insns),
        instructions=insns,
    )


def infer_sdk_min_from_cond(cond: str, edge: str) -> Optional[int]:
    """
    Infer a minimum SDK hint from simple conditions like '$i0_<_22'.
    For FALSE edge on '< N', branch implies SDK >= N.
    """
    cond = (cond or "").strip()
    # Common token shape from branch logs: $i0_<_22
    match = re.search(r"<_\s*([0-9]+)", cond)
    if match and edge == "FALSE":
        return int(match.group(1))
    return None


def make_prompt(record: BranchRecord, ctx: Optional[MethodContext]) -> str:
    class_for_prompt = record.class_name
    method_for_prompt = record.method_name

    if ctx is not None:
        class_for_prompt = ctx.class_name
        method_for_prompt = ctx.method_name

    insn_block = "(method body unavailable)"
    if ctx is not None and ctx.instructions:
        insn_block = "\n".join(ctx.instructions)

    sdk_hint = infer_sdk_min_from_cond(record.cond, record.edge)
    sdk_hint_line = (
        f"- Inferred SDK minimum for this edge: {sdk_hint}\n"
        if sdk_hint is not None
        else "- Inferred SDK minimum for this edge: unknown\n"
    )

    return (
        "### Task: Generate Android test cases for a cold branch\n\n"
        "You are a mobile security testing expert. Analyze the cold branch context below\n"
        "and propose concrete, executable tests to trigger it.\n\n"
        "Output requirements:\n"
        "- Return STRICT JSON only (no markdown, no code fences, no comments).\n"
        "- Return a JSON array with 3-6 objects.\n"
        "- Include BOTH kinds across the array: `adb_probe` and `automation_draft`.\n"
        "- Prefer non-destructive steps first.\n"
        "- Commands must be directly executable shell commands (no pseudocode).\n\n"
        "App context placeholders (fill or infer safely):\n"
        "- package: <APP_PACKAGE>\n"
        "- main activity: <MAIN_ACTIVITY>\n"
        "- device/os: <DEVICE_AND_ANDROID_VERSION>\n"
        "- allowed tools: adb shell am, adb shell cmd, adb shell input, logcat\n\n"
        f"Cold branch record:\n- Raw: {record.raw}\n"
        f"- Branch type: {record.branch_type}\n"
        f"- Edge: {record.edge}\n"
        f"- Condition token: {record.cond}\n"
        f"- UID: {record.uid}\n"
        f"{sdk_hint_line}"
        "\n"
        f"Method context:\n- Class: {class_for_prompt}\n"
        f"- Method: {method_for_prompt}\n"
        f"- Return type: {record.return_type}\n"
        f"- Params: {record.params}\n"
        f"- Descriptor: {(ctx.descriptor if ctx else 'N/A')}\n\n"
        "Instructions:\n"
        f"{insn_block}\n\n"
        "JSON schema for EACH object:\n"
        "{\n"
        "  \"test_id\": \"string\",\n"
        "  \"type\": \"adb_probe|automation_draft\",\n"
        "  \"target_uid\": \""
        f"{record.uid}"
        "\",\n"
        "  \"target_edge\": \""
        f"{record.edge}"
        "\",\n"
        "  \"requires_sdk_min\": number|null,\n"
        "  \"preconditions\": [\"string\", \"...\"],\n"
        "  \"commands\": [\"string\", \"...\"],\n"
        "  \"expected_signal\": [\"string\", \"...\"],\n"
        "  \"verification_steps\": [\"string\", \"...\"],\n"
        "  \"coverage_verification\": [\"string\", \"...\"],\n"
        "  \"risk\": \"low|medium|high\"\n"
        "}\n\n"
        "Coverage verification requirement (must include):\n"
        "- Re-run branch log collection after probe.\n"
        "- Re-run branch_coverage_analysis.py.\n"
        "- Assert this branch UID+EDGE is no longer uncovered, or explain why evidence is inconclusive.\n"
    )


def to_json_record(record: BranchRecord, ctx: Optional[MethodContext], prompt: str) -> Dict[str, object]:
    return {
        "raw_branch": record.raw,
        "class_name": record.class_name,
        "method_name": record.method_name,
        "return_type": record.return_type,
        "params": record.params,
        "branch_type": record.branch_type,
        "edge": record.edge,
        "uid": record.uid,
        "cond": record.cond,
        "method_descriptor": ctx.descriptor if ctx else None,
        "instruction_count": ctx.instruction_count if ctx else 0,
        "instructions": ctx.instructions if ctx else [],
        "prompt": prompt,
    }


def resolve_output_path(base_dir: str, target_path: str) -> str:
    """Resolve a potentially relative output path under base_dir."""
    if os.path.isabs(target_path):
        return target_path
    return os.path.join(base_dir, target_path)


def run(
    apk_path: str,
    uncovered_path: str,
    top_n: int,
    max_instructions: int,
    out_md: str,
    out_jsonl: Optional[str],
    out_dir: Optional[str],
) -> None:
    records = read_uncovered_file(uncovered_path)
    if not records:
        raise RuntimeError("No parsable uncovered branches were found.")

    print(f"Loaded uncovered branches: {len(records)}")
    print(f"Analyzing APK: {apk_path}")

    # By default, write artifacts next to the APK (useful for instrumented_apk workflows).
    base_output_dir = out_dir or os.path.dirname(os.path.abspath(apk_path)) or os.getcwd()
    os.makedirs(base_output_dir, exist_ok=True)

    out_md_resolved = resolve_output_path(base_output_dir, out_md)
    out_jsonl_resolved = (
        resolve_output_path(base_output_dir, out_jsonl) if out_jsonl else None
    )

    _, _, dx = AnalyzeAPK(apk_path)
    method_index = build_method_index(dx)

    selected = records[:top_n] if top_n > 0 else records
    generated: List[Tuple[BranchRecord, Optional[MethodContext], str]] = []

    misses = 0
    for rec in tqdm(selected, desc="Generating prompts", unit="branch"):
        candidates = method_index.get((rec.class_name, rec.method_name), [])
        ctx = extract_method_context(candidates[0], max_instructions) if candidates else None
        if ctx is None:
            misses += 1
        prompt = make_prompt(rec, ctx)
        generated.append((rec, ctx, prompt))

    with open(out_md_resolved, "w", encoding="utf-8") as md:
        md.write("# Cold Path Prompts\n\n")
        md.write(f"- APK: `{apk_path}`\n")
        md.write(f"- Uncovered source: `{uncovered_path}`\n")
        md.write(f"- Records generated: {len(generated)}\n")
        md.write(f"- Method context misses: {misses}\n\n")

        for idx, (rec, ctx, prompt) in enumerate(generated, start=1):
            md.write(f"## Cold Branch {idx}\n\n")
            md.write(f"- Raw: `{rec.raw}`\n")
            md.write(f"- Context found: `{ctx is not None}`\n\n")
            md.write(prompt)
            md.write("\n\n---\n\n")

    print(f"Wrote markdown prompts: {out_md_resolved}")

    if out_jsonl_resolved:
        with open(out_jsonl_resolved, "w", encoding="utf-8") as jh:
            for rec, ctx, prompt in generated:
                jh.write(json.dumps(to_json_record(rec, ctx, prompt), ensure_ascii=True) + "\n")
        print(f"Wrote JSONL prompts: {out_jsonl_resolved}")

    print("Done.")


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Cold Path Extractor (AndroGuard-based)")
    parser.add_argument("--apk", required=True, help="Path to APK")
    parser.add_argument(
        "--uncovered",
        required=True,
        help="Path to uncovered_branches.txt or uncovered_branches.csv",
    )
    parser.add_argument("--top", type=int, default=20, help="How many uncovered branches to generate prompts for")
    parser.add_argument(
        "--max-instructions",
        type=int,
        default=120,
        help="Maximum bytecode instructions per method to include in prompt",
    )
    parser.add_argument("--out-md", default="cold_path_prompts.md", help="Output markdown file")
    parser.add_argument("--out-jsonl", default="cold_path_prompts.jsonl", help="Optional output JSONL file")
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory for generated files (default: same directory as --apk)",
    )
    return parser


def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    run(
        apk_path=args.apk,
        uncovered_path=args.uncovered,
        top_n=args.top,
        max_instructions=args.max_instructions,
        out_md=args.out_md,
        out_jsonl=args.out_jsonl,
        out_dir=args.out_dir,
    )


if __name__ == "__main__":
    main()
